SELECT        RENTAL.RENTAL_ID, RENTAL.CUSTOMER_ID, RENTAL.MOVIE_ID, RENTAL.DATE_RENTED
FROM            MOVIE_INFO INNER JOIN
                         RENTAL ON MOVIE_INFO.MOVIE_ID = RENTAL.MOVIE_ID
WHERE        (RENTAL.DATE_RETURNED IS NULL
			OR RENTAL.DATE_RETURNED LIKE ' ')
ORDER BY MOVIE_INFO.RENTED, RENTAL.DATE_RENTED DESC