SELECT	RENTAL.CUSTOMER_ID, 
		CUSTOMER_INFO.CUSTOMER_FNAME, 
		CUSTOMER_INFO.CUSTOMER_LNAME,
		RENTAL.MOVIE_ID,
		MOVIE_INFO.MOVIE_TITLE,
		RENTAL.DATE_RENTED,
		RENTAL.DATE_RETURNED
		FROM	RENTAL,  
				MOVIE_INFO,
				CUSTOMER_INFO
		WHERE	RENTAL.CUSTOMER_ID = CUSTOMER_INFO.CUSTOMER_ID
				AND RENTAL.MOVIE_ID = MOVIE_INFO.MOVIE_ID
				ORDER BY RENTAL.MOVIE_ID, RENTAL.DATE_RENTED DESC